"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.uploadCategories = void 0;
const https_1 = require("firebase-functions/v2/https");
const firestore_1 = require("firebase-admin/firestore");
exports.uploadCategories = (0, https_1.onCall)(async (request) => {
    const categories = [
        {
            name: "INCOME_DIVIDENDS",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_DIVIDENDS",
            description: "Dividends from investment accounts",
            type: "Income",
            second_category: "Dividend Payment",
            first_category: "Interest Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 1
        },
        {
            name: "INCOME_INTEREST_EARNED",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_INTEREST_EARNED",
            description: "Income from interest on savings accounts",
            type: "Income",
            second_category: "Interest Earned",
            first_category: "Interest Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 2
        },
        {
            name: "INCOME_RETIREMENT_PENSION",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_RETIREMENT_PENSION",
            description: "Income from pension payments",
            type: "Income",
            second_category: "Retirement Pension",
            first_category: "Interest Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 3
        },
        {
            name: "INCOME_TAX_REFUND",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_TAX_REFUND",
            description: "Income from tax refunds",
            type: "Income",
            second_category: "Tax Refund",
            first_category: "Government Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 4
        },
        {
            name: "INCOME_UNEMPLOYMENT",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_UNEMPLOYMENT",
            description: "Income from unemployment benefits, including unemployment insurance and healthcare",
            type: "Income",
            second_category: "Unemployment Payment",
            first_category: "Government Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 5
        },
        {
            name: "INCOME_WAGES",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_WAGES",
            description: "Income from salaries, gig-economy work, and tips earned",
            type: "Income",
            second_category: "Income",
            first_category: "Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 6
        },
        {
            name: "INCOME_OTHER_INCOME",
            primary_plaid_category: "INCOME",
            detailed_plaid_category: "INCOME_OTHER_INCOME",
            description: "Other miscellaneous income, including alimony, social security, child support, and rental",
            type: "Income",
            second_category: "Other Income",
            first_category: "Government Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 7
        },
        {
            name: "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
            primary_plaid_category: "TRANSFER_IN",
            detailed_plaid_category: "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
            description: "Loans and cash advances deposited into a bank account",
            type: "Income",
            second_category: "Loans and Cash Advance",
            first_category: "Loan Income",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 8
        },
        {
            name: "TRANSFER_IN_DEPOSIT",
            primary_plaid_category: "TRANSFER_IN",
            detailed_plaid_category: "TRANSFER_IN_DEPOSIT",
            description: "Cash, checks, and ATM deposits into a bank account",
            type: "Income",
            second_category: "Cash or Check Deposit",
            first_category: "Bank Deposit",
            overall_category: "Income",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 9
        },
        {
            name: "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
            primary_plaid_category: "TRANSFER_IN",
            detailed_plaid_category: "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
            description: "Inbound transfers to an investment or retirement account",
            type: "Income",
            second_category: "Retirement Transfer",
            first_category: "Inbound Transfer",
            overall_category: "Inbound Account Transfer",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 10
        },
        {
            name: "TRANSFER_IN_SAVINGS",
            primary_plaid_category: "TRANSFER_IN",
            detailed_plaid_category: "TRANSFER_IN_SAVINGS",
            description: "Inbound transfers to a savings account",
            type: "Income",
            second_category: "Savings Transfer",
            first_category: "Inbound Transfer",
            overall_category: "Inbound Account Transfer",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 11
        },
        {
            name: "TRANSFER_IN_ACCOUNT_TRANSFER",
            primary_plaid_category: "TRANSFER_IN",
            detailed_plaid_category: "TRANSFER_IN_ACCOUNT_TRANSFER",
            description: "General inbound transfers from another account",
            type: "Income",
            second_category: "Account Transfer",
            first_category: "Inbound Transfer",
            overall_category: "Inbound Account Transfer",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 12
        },
        {
            name: "TRANSFER_IN_OTHER_TRANSFER_IN",
            primary_plaid_category: "TRANSFER_IN",
            detailed_plaid_category: "TRANSFER_IN_OTHER_TRANSFER_IN",
            description: "Other miscellaneous inbound transactions",
            type: "Income",
            second_category: "Transfer Transaction",
            first_category: "Inbound Transfer",
            overall_category: "Inbound Account Transfer",
            visible_by_default: false,
            budget_selection: false,
            income_selection: true,
            index: 13
        },
        {
            name: "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
            primary_plaid_category: "TRANSFER_OUT",
            detailed_plaid_category: "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
            description: "Transfers to an investment or retirement account, including investment apps such as Acorns, Betterment",
            type: "Outflow",
            second_category: "Investment Transfer",
            first_category: "Outbound Transfer",
            overall_category: "Outbound Account Transfer",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 14
        },
        {
            name: "TRANSFER_OUT_SAVINGS",
            primary_plaid_category: "TRANSFER_OUT",
            detailed_plaid_category: "TRANSFER_OUT_SAVINGS",
            description: "Outbound transfers to savings accounts",
            type: "Outflow",
            second_category: "Savings Transfer",
            first_category: "Outbound Transfer",
            overall_category: "Outbound Account Transfer",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 15
        },
        {
            name: "TRANSFER_OUT_WITHDRAWAL",
            primary_plaid_category: "TRANSFER_OUT",
            detailed_plaid_category: "TRANSFER_OUT_WITHDRAWAL",
            description: "Withdrawals from a bank account",
            type: "Outflow",
            second_category: "Cash Withdrawl",
            first_category: "Outbound Transfer",
            overall_category: "Outbound Account Transfer",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 16
        },
        {
            name: "TRANSFER_OUT_ACCOUNT_TRANSFER",
            primary_plaid_category: "TRANSFER_OUT",
            detailed_plaid_category: "TRANSFER_OUT_ACCOUNT_TRANSFER",
            description: "General outbound transfers to another account",
            type: "Outflow",
            second_category: "Account Transfer",
            first_category: "Outbound Transfer",
            overall_category: "Outbound Account Transfer",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 17
        },
        {
            name: "TRANSFER_OUT_OTHER_TRANSFER_OUT",
            primary_plaid_category: "TRANSFER_OUT",
            detailed_plaid_category: "TRANSFER_OUT_OTHER_TRANSFER_OUT",
            description: "Other miscellaneous outbound transactions",
            type: "Outflow",
            second_category: "Other Transactions",
            first_category: "Outbound Transfer",
            overall_category: "Outbound Account Transfer",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 18
        },
        {
            name: "LOAN_PAYMENTS_CAR_PAYMENT",
            primary_plaid_category: "LOAN_PAYMENTS",
            detailed_plaid_category: "LOAN_PAYMENTS_CAR_PAYMENT",
            description: "Car loans and leases",
            type: "Outflow",
            second_category: "Car Payment",
            first_category: "Loan Payment",
            overall_category: "Loan Payment",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 19
        },
        {
            name: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
            primary_plaid_category: "LOAN_PAYMENTS",
            detailed_plaid_category: "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
            description: "Payments to a credit card. These are positive amounts for credit card subtypes and negative for depository subtypes",
            type: "Outflow",
            second_category: "Credit Card Payment",
            first_category: "Loan Payment",
            overall_category: "Loan Payment",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 20
        },
        {
            name: "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
            primary_plaid_category: "LOAN_PAYMENTS",
            detailed_plaid_category: "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
            description: "Personal loans, including cash advances and buy now pay later repayments",
            type: "Outflow",
            second_category: "Loan Payment",
            first_category: "Loan Payment",
            overall_category: "Loan Payment",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 21
        },
        {
            name: "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
            primary_plaid_category: "LOAN_PAYMENTS",
            detailed_plaid_category: "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
            description: "Payments on mortgages",
            type: "Outflow",
            second_category: "Mortgage Payment",
            first_category: "Loan Payment",
            overall_category: "Loan Payment",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 22
        },
        {
            name: "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
            primary_plaid_category: "LOAN_PAYMENTS",
            detailed_plaid_category: "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
            description: "Payments on student loans. For college tuition, refer to \"General Services - Education\"",
            type: "Outflow",
            second_category: "Student Loan Payment",
            first_category: "Loan Payment",
            overall_category: "Loan Payment",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 23
        },
        {
            name: "LOAN_PAYMENTS_OTHER_PAYMENT",
            primary_plaid_category: "LOAN_PAYMENTS",
            detailed_plaid_category: "LOAN_PAYMENTS_OTHER_PAYMENT",
            description: "Other miscellaneous debt payments",
            type: "Outflow",
            second_category: "Debt Payment",
            first_category: "Loan Payment",
            overall_category: "Loan Payment",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 24
        },
        {
            name: "BANK_FEES_ATM_FEES",
            primary_plaid_category: "BANK_FEES",
            detailed_plaid_category: "BANK_FEES_ATM_FEES",
            description: "Fees incurred for out-of-network ATMs",
            type: "Outflow",
            second_category: "ATM Fee",
            first_category: "Bank Fees",
            overall_category: "Bank Fees",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 25
        },
        {
            name: "BANK_FEES_FOREIGN_TRANSACTION_FEES",
            primary_plaid_category: "BANK_FEES",
            detailed_plaid_category: "BANK_FEES_FOREIGN_TRANSACTION_FEES",
            description: "Fees incurred on non-domestic transactions",
            type: "Outflow",
            second_category: "Foreign Transaction Fee",
            first_category: "Bank Fees",
            overall_category: "Bank Fees",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 26
        },
        {
            name: "BANK_FEES_INSUFFICIENT_FUNDS",
            primary_plaid_category: "BANK_FEES",
            detailed_plaid_category: "BANK_FEES_INSUFFICIENT_FUNDS",
            description: "Fees relating to insufficient funds",
            type: "Outflow",
            second_category: "Insufficient Funds Fee",
            first_category: "Bank Fees",
            overall_category: "Bank Fees",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 27
        },
        {
            name: "BANK_FEES_INTEREST_CHARGE",
            primary_plaid_category: "BANK_FEES",
            detailed_plaid_category: "BANK_FEES_INTEREST_CHARGE",
            description: "Fees incurred for interest on purchases, including not-paid-in-full or interest on cash advances",
            type: "Outflow",
            second_category: "Interest Fees",
            first_category: "Bank Fees",
            overall_category: "Bank Fees",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 28
        },
        {
            name: "BANK_FEES_OVERDRAFT_FEES",
            primary_plaid_category: "BANK_FEES",
            detailed_plaid_category: "BANK_FEES_OVERDRAFT_FEES",
            description: "Fees incurred when an account is in overdraft",
            type: "Outflow",
            second_category: "Overdraft Fee",
            first_category: "Bank Fees",
            overall_category: "Bank Fees",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 29
        },
        {
            name: "BANK_FEES_OTHER_BANK_FEES",
            primary_plaid_category: "BANK_FEES",
            detailed_plaid_category: "BANK_FEES_OTHER_BANK_FEES",
            description: "Other miscellaneous bank fees",
            type: "Outflow",
            second_category: "Bank Fees",
            first_category: "Bank Fees",
            overall_category: "Bank Fees",
            visible_by_default: true,
            budget_selection: true,
            income_selection: false,
            index: 30
        }
        // ... I'll continue with more categories in the next part due to length
    ];
    try {
        const db = (0, firestore_1.getFirestore)();
        const batch = db.batch();
        categories.forEach((category) => {
            const categoryRef = db.collection('categories').doc(category.name);
            batch.set(categoryRef, category);
        });
        await batch.commit();
        return { success: true, count: categories.length };
    }
    catch (error) {
        console.error('Error uploading categories:', error);
        throw new https_1.HttpsError('internal', 'Failed to upload categories');
    }
});
//# sourceMappingURL=uploadCategories.js.map