/**
 * Manual Outflow Resolver
 *
 * READ-ONLY impact analysis for creating a user-entered bill. A new bill has no
 * stored dependents: its periods are generated by the outflow-created trigger
 * and derive-on-read picks it up via the recurring-updated cache bump.
 *
 * @module resolvers/recurring/manual_outflow
 */
import { TraceContext, DependencyResult } from "../../types";
/**
 * Resolves dependencies for creating a manual bill (none).
 *
 * @param _ctx - Trace context
 * @returns No dependencies
 */
export declare function resolve_create_manual_outflow_dependencies(_ctx: TraceContext): Promise<DependencyResult>;
//# sourceMappingURL=manual_outflow.resolver.d.ts.map