import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { getFirestore } from 'firebase-admin/firestore';

// Embedded categories data (all 111 categories).
// GENERATED from live Firestore by scripts/gen-categories-seed.js — do NOT hand-edit;
// regenerate after any change to the categories collection so the seed never drifts.
const CATEGORIES_DATA = {
  "INCOME_DIVIDENDS": {
    "name": "INCOME_DIVIDENDS",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_DIVIDENDS",
    "description": "Dividends from investment accounts",
    "type": "Income",
    "second_category": "Dividend Payment",
    "first_category": "Interest Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "interest_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 1,
    "isActive": true
  },
  "INCOME_INTEREST_EARNED": {
    "name": "INCOME_INTEREST_EARNED",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_INTEREST_EARNED",
    "description": "Income from interest on savings accounts",
    "type": "Income",
    "second_category": "Interest Earned",
    "first_category": "Interest Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "interest_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 2,
    "isActive": true
  },
  "INCOME_RETIREMENT_PENSION": {
    "name": "INCOME_RETIREMENT_PENSION",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_RETIREMENT_PENSION",
    "description": "Income from pension payments",
    "type": "Income",
    "second_category": "Retirement Pension",
    "first_category": "Interest Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "interest_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 3,
    "isActive": true
  },
  "INCOME_TAX_REFUND": {
    "name": "INCOME_TAX_REFUND",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_TAX_REFUND",
    "description": "Income from tax refunds",
    "type": "Income",
    "second_category": "Tax Refund",
    "first_category": "Government Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "government_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 4,
    "isActive": true
  },
  "INCOME_UNEMPLOYMENT": {
    "name": "INCOME_UNEMPLOYMENT",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_UNEMPLOYMENT",
    "description": "Income from unemployment benefits, including unemployment insurance and healthcare",
    "type": "Income",
    "second_category": "Unemployment Payment",
    "first_category": "Government Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "government_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 5,
    "isActive": true
  },
  "INCOME_WAGES": {
    "name": "INCOME_WAGES",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_WAGES",
    "description": "Income from salaries, gig-economy work, and tips earned",
    "type": "Income",
    "second_category": "Wages",
    "first_category": "Wages",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "wages",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 6,
    "isActive": true
  },
  "INCOME_OTHER_INCOME": {
    "name": "INCOME_OTHER_INCOME",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_OTHER_INCOME",
    "description": "Other miscellaneous income, including alimony, social security, child support, and rental",
    "type": "Income",
    "second_category": "Other Income",
    "first_category": "Government Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "government_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 7,
    "isActive": true
  },
  "TRANSFER_IN_CASH_ADVANCES_AND_LOANS": {
    "name": "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
    "description": "Loans and cash advances deposited into a bank account",
    "type": "Income",
    "second_category": "Loans and Cash Advance",
    "first_category": "Loan Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "loan_income",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 8,
    "isActive": true
  },
  "TRANSFER_IN_DEPOSIT": {
    "name": "TRANSFER_IN_DEPOSIT",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_DEPOSIT",
    "description": "Cash, checks, and ATM deposits into a bank account",
    "type": "Income",
    "second_category": "Cash or Check Deposit",
    "first_category": "Bank Deposit",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "bank_deposit",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 9,
    "isActive": true
  },
  "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS": {
    "name": "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
    "description": "Inbound transfers to an investment or retirement account",
    "type": "Income",
    "second_category": "Retirement Transfer",
    "first_category": "Inbound Transfer",
    "overall_category": "Inbound Account Transfer",
    "overallCategoryId": "inbound_account_transfer",
    "firstCategoryId": "inbound_transfer",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 10,
    "isActive": true
  },
  "TRANSFER_IN_SAVINGS": {
    "name": "TRANSFER_IN_SAVINGS",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_SAVINGS",
    "description": "Inbound transfers to a savings account",
    "type": "Income",
    "second_category": "Savings Transfer",
    "first_category": "Inbound Transfer",
    "overall_category": "Inbound Account Transfer",
    "overallCategoryId": "inbound_account_transfer",
    "firstCategoryId": "inbound_transfer",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 11,
    "isActive": true
  },
  "TRANSFER_IN_ACCOUNT_TRANSFER": {
    "name": "TRANSFER_IN_ACCOUNT_TRANSFER",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_ACCOUNT_TRANSFER",
    "description": "General inbound transfers from another account",
    "type": "Income",
    "second_category": "Account Transfer",
    "first_category": "Inbound Transfer",
    "overall_category": "Inbound Account Transfer",
    "overallCategoryId": "inbound_account_transfer",
    "firstCategoryId": "inbound_transfer",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 12,
    "isActive": true
  },
  "TRANSFER_IN_OTHER_TRANSFER_IN": {
    "name": "TRANSFER_IN_OTHER_TRANSFER_IN",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_OTHER_TRANSFER_IN",
    "description": "Other miscellaneous inbound transactions",
    "type": "Income",
    "second_category": "Transfer Transaction",
    "first_category": "Inbound Transfer",
    "overall_category": "Inbound Account Transfer",
    "overallCategoryId": "inbound_account_transfer",
    "firstCategoryId": "inbound_transfer",
    "visible_by_default": false,
    "budget_selection": false,
    "income_selection": true,
    "index": 13,
    "isActive": true
  },
  "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS": {
    "name": "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
    "primary_plaid_category": "TRANSFER_OUT",
    "detailed_plaid_category": "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
    "description": "Transfers to an investment or retirement account, including investment apps such as Acorns, Betterment",
    "type": "Outflow",
    "second_category": "Investment Transfer",
    "first_category": "Outbound Transfer",
    "overall_category": "Outbound Account Transfer",
    "overallCategoryId": "outbound_account_transfer",
    "firstCategoryId": "outbound_transfer",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 14,
    "isActive": true
  },
  "TRANSFER_OUT_SAVINGS": {
    "name": "TRANSFER_OUT_SAVINGS",
    "primary_plaid_category": "TRANSFER_OUT",
    "detailed_plaid_category": "TRANSFER_OUT_SAVINGS",
    "description": "Outbound transfers to savings accounts",
    "type": "Outflow",
    "second_category": "Savings Transfer",
    "first_category": "Outbound Transfer",
    "overall_category": "Outbound Account Transfer",
    "overallCategoryId": "outbound_account_transfer",
    "firstCategoryId": "outbound_transfer",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 15,
    "isActive": true
  },
  "TRANSFER_OUT_WITHDRAWAL": {
    "name": "TRANSFER_OUT_WITHDRAWAL",
    "primary_plaid_category": "TRANSFER_OUT",
    "detailed_plaid_category": "TRANSFER_OUT_WITHDRAWAL",
    "description": "Withdrawals from a bank account",
    "type": "Outflow",
    "second_category": "Cash Withdrawl",
    "first_category": "Outbound Transfer",
    "overall_category": "Outbound Account Transfer",
    "overallCategoryId": "outbound_account_transfer",
    "firstCategoryId": "outbound_transfer",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 16,
    "isActive": true
  },
  "TRANSFER_OUT_ACCOUNT_TRANSFER": {
    "name": "TRANSFER_OUT_ACCOUNT_TRANSFER",
    "primary_plaid_category": "TRANSFER_OUT",
    "detailed_plaid_category": "TRANSFER_OUT_ACCOUNT_TRANSFER",
    "description": "General outbound transfers to another account",
    "type": "Outflow",
    "second_category": "Account Transfer",
    "first_category": "Outbound Transfer",
    "overall_category": "Outbound Account Transfer",
    "overallCategoryId": "outbound_account_transfer",
    "firstCategoryId": "outbound_transfer",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 17,
    "isActive": true
  },
  "TRANSFER_OUT_OTHER_TRANSFER_OUT": {
    "name": "TRANSFER_OUT_OTHER_TRANSFER_OUT",
    "primary_plaid_category": "TRANSFER_OUT",
    "detailed_plaid_category": "TRANSFER_OUT_OTHER_TRANSFER_OUT",
    "description": "Other miscellaneous outbound transactions",
    "type": "Outflow",
    "second_category": "Other Transactions",
    "first_category": "Outbound Transfer",
    "overall_category": "Outbound Account Transfer",
    "overallCategoryId": "outbound_account_transfer",
    "firstCategoryId": "outbound_transfer",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 18,
    "isActive": true
  },
  "LOAN_PAYMENTS_CAR_PAYMENT": {
    "name": "LOAN_PAYMENTS_CAR_PAYMENT",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_CAR_PAYMENT",
    "description": "Car loans and leases",
    "type": "Outflow",
    "second_category": "Car Payment",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 19,
    "isActive": true
  },
  "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT": {
    "name": "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
    "description": "Payments to a credit card. These are positive amounts for credit card subtypes and negative for depository subtypes",
    "type": "Outflow",
    "second_category": "Credit Card Payment",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 20,
    "isActive": true
  },
  "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT": {
    "name": "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
    "description": "Personal loans, including cash advances and buy now pay later repayments",
    "type": "Outflow",
    "second_category": "Loan Payment",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 21,
    "isActive": true
  },
  "LOAN_PAYMENTS_MORTGAGE_PAYMENT": {
    "name": "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
    "description": "Payments on mortgages",
    "type": "Outflow",
    "second_category": "Mortgage Payment",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 22,
    "isActive": true
  },
  "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT": {
    "name": "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
    "description": "Payments on student loans. For college tuition, refer to \"General Services - Education\"",
    "type": "Outflow",
    "second_category": "Student Loan Payment",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 23,
    "isActive": true
  },
  "LOAN_PAYMENTS_OTHER_PAYMENT": {
    "name": "LOAN_PAYMENTS_OTHER_PAYMENT",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_OTHER_PAYMENT",
    "description": "Other miscellaneous debt payments",
    "type": "Outflow",
    "second_category": "Debt Payment",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 24,
    "isActive": true
  },
  "BANK_FEES_ATM_FEES": {
    "name": "BANK_FEES_ATM_FEES",
    "primary_plaid_category": "BANK_FEES",
    "detailed_plaid_category": "BANK_FEES_ATM_FEES",
    "description": "Fees incurred for out-of-network ATMs",
    "type": "Outflow",
    "second_category": "ATM Fee",
    "first_category": "Bank Fees",
    "overall_category": "Bank Fees",
    "overallCategoryId": "bank_fees",
    "firstCategoryId": "bank_fees",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 25,
    "isActive": true
  },
  "BANK_FEES_FOREIGN_TRANSACTION_FEES": {
    "name": "BANK_FEES_FOREIGN_TRANSACTION_FEES",
    "primary_plaid_category": "BANK_FEES",
    "detailed_plaid_category": "BANK_FEES_FOREIGN_TRANSACTION_FEES",
    "description": "Fees incurred on non-domestic transactions",
    "type": "Outflow",
    "second_category": "Foreign Transaction Fee",
    "first_category": "Bank Fees",
    "overall_category": "Bank Fees",
    "overallCategoryId": "bank_fees",
    "firstCategoryId": "bank_fees",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 26,
    "isActive": true
  },
  "BANK_FEES_INSUFFICIENT_FUNDS": {
    "name": "BANK_FEES_INSUFFICIENT_FUNDS",
    "primary_plaid_category": "BANK_FEES",
    "detailed_plaid_category": "BANK_FEES_INSUFFICIENT_FUNDS",
    "description": "Fees relating to insufficient funds",
    "type": "Outflow",
    "second_category": "Insufficient Funds Fee",
    "first_category": "Bank Fees",
    "overall_category": "Bank Fees",
    "overallCategoryId": "bank_fees",
    "firstCategoryId": "bank_fees",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 27,
    "isActive": true
  },
  "BANK_FEES_INTEREST_CHARGE": {
    "name": "BANK_FEES_INTEREST_CHARGE",
    "primary_plaid_category": "BANK_FEES",
    "detailed_plaid_category": "BANK_FEES_INTEREST_CHARGE",
    "description": "Fees incurred for interest on purchases, including not-paid-in-full or interest on cash advances",
    "type": "Outflow",
    "second_category": "Interest Fees",
    "first_category": "Bank Fees",
    "overall_category": "Bank Fees",
    "overallCategoryId": "bank_fees",
    "firstCategoryId": "bank_fees",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 28,
    "isActive": true
  },
  "BANK_FEES_OVERDRAFT_FEES": {
    "name": "BANK_FEES_OVERDRAFT_FEES",
    "primary_plaid_category": "BANK_FEES",
    "detailed_plaid_category": "BANK_FEES_OVERDRAFT_FEES",
    "description": "Fees incurred when an account is in overdraft",
    "type": "Outflow",
    "second_category": "Overdraft Fee",
    "first_category": "Bank Fees",
    "overall_category": "Bank Fees",
    "overallCategoryId": "bank_fees",
    "firstCategoryId": "bank_fees",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 29,
    "isActive": true
  },
  "BANK_FEES_OTHER_BANK_FEES": {
    "name": "BANK_FEES_OTHER_BANK_FEES",
    "primary_plaid_category": "BANK_FEES",
    "detailed_plaid_category": "BANK_FEES_OTHER_BANK_FEES",
    "description": "Other miscellaneous bank fees",
    "type": "Outflow",
    "second_category": "Bank Fees",
    "first_category": "Bank Fees",
    "overall_category": "Bank Fees",
    "overallCategoryId": "bank_fees",
    "firstCategoryId": "bank_fees",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 30,
    "isActive": true
  },
  "ENTERTAINMENT_CASINOS_AND_GAMBLING": {
    "name": "ENTERTAINMENT_CASINOS_AND_GAMBLING",
    "primary_plaid_category": "ENTERTAINMENT",
    "detailed_plaid_category": "ENTERTAINMENT_CASINOS_AND_GAMBLING",
    "description": "Gambling, casinos, and sports betting",
    "type": "Outflow",
    "second_category": "Gambling",
    "first_category": "Gambling",
    "overall_category": "Gambling",
    "overallCategoryId": "gambling",
    "firstCategoryId": "gambling",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 31,
    "isActive": true
  },
  "ENTERTAINMENT_MUSIC_AND_AUDIO": {
    "name": "ENTERTAINMENT_MUSIC_AND_AUDIO",
    "primary_plaid_category": "ENTERTAINMENT",
    "detailed_plaid_category": "ENTERTAINMENT_MUSIC_AND_AUDIO",
    "description": "Digital and in-person music purchases, including music streaming services",
    "type": "Outflow",
    "second_category": "Digital Music",
    "first_category": "Digital Music",
    "overall_category": "Entertainment",
    "overallCategoryId": "entertainment",
    "firstCategoryId": "digital_music",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 32,
    "isActive": true
  },
  "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS": {
    "name": "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
    "primary_plaid_category": "ENTERTAINMENT",
    "detailed_plaid_category": "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
    "description": "Purchases made at sporting events, music venues, concerts, museums, and amusement parks",
    "type": "Outflow",
    "second_category": "Event Tickets",
    "first_category": "Entertainment",
    "overall_category": "Entertainment",
    "overallCategoryId": "entertainment",
    "firstCategoryId": "entertainment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 33,
    "isActive": true
  },
  "ENTERTAINMENT_TV_AND_MOVIES": {
    "name": "ENTERTAINMENT_TV_AND_MOVIES",
    "primary_plaid_category": "ENTERTAINMENT",
    "detailed_plaid_category": "ENTERTAINMENT_TV_AND_MOVIES",
    "description": "In home movie streaming services and movie theaters",
    "type": "Outflow",
    "second_category": "Movies and Entertainment",
    "first_category": "Entertainment",
    "overall_category": "Entertainment",
    "overallCategoryId": "entertainment",
    "firstCategoryId": "entertainment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 34,
    "isActive": true
  },
  "ENTERTAINMENT_VIDEO_GAMES": {
    "name": "ENTERTAINMENT_VIDEO_GAMES",
    "primary_plaid_category": "ENTERTAINMENT",
    "detailed_plaid_category": "ENTERTAINMENT_VIDEO_GAMES",
    "description": "Digital and in-person video game purchases",
    "type": "Outflow",
    "second_category": "Video Games",
    "first_category": "Video Games",
    "overall_category": "Video Games",
    "overallCategoryId": "video_games",
    "firstCategoryId": "video_games",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 35,
    "isActive": true
  },
  "ENTERTAINMENT_OTHER_ENTERTAINMENT": {
    "name": "ENTERTAINMENT_OTHER_ENTERTAINMENT",
    "primary_plaid_category": "ENTERTAINMENT",
    "detailed_plaid_category": "ENTERTAINMENT_OTHER_ENTERTAINMENT",
    "description": "Other miscellaneous entertainment purchases, including night life and adult entertainment",
    "type": "Outflow",
    "second_category": "Night Life",
    "first_category": "Entertainment",
    "overall_category": "Entertainment",
    "overallCategoryId": "entertainment",
    "firstCategoryId": "entertainment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 36,
    "isActive": true
  },
  "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR": {
    "name": "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR",
    "description": "Beer, Wine & Liquor Stores",
    "type": "Outflow",
    "second_category": "Alcohol",
    "first_category": "Alcohol",
    "overall_category": "Alcohol",
    "overallCategoryId": "alcohol",
    "firstCategoryId": "alcohol",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 37,
    "isActive": true
  },
  "FOOD_AND_DRINK_COFFEE": {
    "name": "FOOD_AND_DRINK_COFFEE",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_COFFEE",
    "description": "Purchases at coffee shops or cafes",
    "type": "Outflow",
    "second_category": "Coffee shops",
    "first_category": "Eating Out",
    "overall_category": "Food and Drink",
    "overallCategoryId": "food_and_drink",
    "firstCategoryId": "eating_out",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 38,
    "isActive": true
  },
  "FOOD_AND_DRINK_FAST_FOOD": {
    "name": "FOOD_AND_DRINK_FAST_FOOD",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_FAST_FOOD",
    "description": "Dining expenses for fast food chains",
    "type": "Outflow",
    "second_category": "Fast Food",
    "first_category": "Eating Out",
    "overall_category": "Food and Drink",
    "overallCategoryId": "food_and_drink",
    "firstCategoryId": "eating_out",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 39,
    "isActive": true
  },
  "FOOD_AND_DRINK_GROCERIES": {
    "name": "FOOD_AND_DRINK_GROCERIES",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_GROCERIES",
    "description": "Purchases for fresh produce and groceries, including farmers' markets",
    "type": "Outflow",
    "second_category": "Groceries",
    "first_category": "Groceries",
    "overall_category": "Groceries",
    "overallCategoryId": "groceries",
    "firstCategoryId": "groceries",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 40,
    "isActive": true
  },
  "FOOD_AND_DRINK_RESTAURANT": {
    "name": "FOOD_AND_DRINK_RESTAURANT",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_RESTAURANT",
    "description": "Dining expenses for restaurants, bars, gastropubs, and diners",
    "type": "Outflow",
    "second_category": "Restaurants",
    "first_category": "Eating Out",
    "overall_category": "Food and Drink",
    "overallCategoryId": "food_and_drink",
    "firstCategoryId": "eating_out",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 41,
    "isActive": true
  },
  "FOOD_AND_DRINK_VENDING_MACHINES": {
    "name": "FOOD_AND_DRINK_VENDING_MACHINES",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_VENDING_MACHINES",
    "description": "Purchases made at vending machine operators",
    "type": "Outflow",
    "second_category": "Vending Machines",
    "first_category": "Eating Out",
    "overall_category": "Food and Drink",
    "overallCategoryId": "food_and_drink",
    "firstCategoryId": "eating_out",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 42,
    "isActive": true
  },
  "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK": {
    "name": "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK",
    "primary_plaid_category": "FOOD_AND_DRINK",
    "detailed_plaid_category": "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK",
    "description": "Other miscellaneous food and drink, including desserts, juice bars, and delis",
    "type": "Outflow",
    "second_category": "Eating Out",
    "first_category": "Eating Out",
    "overall_category": "Food and Drink",
    "overallCategoryId": "food_and_drink",
    "firstCategoryId": "eating_out",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 43,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS": {
    "name": "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS",
    "description": "Books, magazines, and news ",
    "type": "Outflow",
    "second_category": "Books and News",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 44,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES": {
    "name": "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES",
    "description": "Apparel, shoes, and jewelry",
    "type": "Outflow",
    "second_category": "Clothing and Accessories",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 45,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_CONVENIENCE_STORES": {
    "name": "GENERAL_MERCHANDISE_CONVENIENCE_STORES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_CONVENIENCE_STORES",
    "description": "Purchases at convenience stores",
    "type": "Outflow",
    "second_category": "Convenience Stores",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 46,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_DEPARTMENT_STORES": {
    "name": "GENERAL_MERCHANDISE_DEPARTMENT_STORES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_DEPARTMENT_STORES",
    "description": "Retail stores with wide ranges of consumer goods, typically specializing in clothing and home goods",
    "type": "Outflow",
    "second_category": "Home Goods",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 47,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_DISCOUNT_STORES": {
    "name": "GENERAL_MERCHANDISE_DISCOUNT_STORES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_DISCOUNT_STORES",
    "description": "Stores selling goods at a discounted price",
    "type": "Outflow",
    "second_category": "Discount Stores",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 48,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_ELECTRONICS": {
    "name": "GENERAL_MERCHANDISE_ELECTRONICS",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_ELECTRONICS",
    "description": "Electronics stores and websites",
    "type": "Outflow",
    "second_category": "Electronics",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 49,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES": {
    "name": "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES",
    "description": "Photo, gifts, cards, and floral stores",
    "type": "Outflow",
    "second_category": "Photos and Gifts",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 50,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_OFFICE_SUPPLIES": {
    "name": "GENERAL_MERCHANDISE_OFFICE_SUPPLIES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_OFFICE_SUPPLIES",
    "description": "Stores that specialize in office goods",
    "type": "Outflow",
    "second_category": "Office Goods",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 51,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES": {
    "name": "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES",
    "description": "Multi-purpose e-commerce platforms such as Etsy, Ebay and Amazon",
    "type": "Outflow",
    "second_category": "E-Commerce",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 52,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_PET_SUPPLIES": {
    "name": "GENERAL_MERCHANDISE_PET_SUPPLIES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_PET_SUPPLIES",
    "description": "Pet supplies and pet food",
    "type": "Outflow",
    "second_category": "Pet Supplies",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 53,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_SPORTING_GOODS": {
    "name": "GENERAL_MERCHANDISE_SPORTING_GOODS",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_SPORTING_GOODS",
    "description": "Sporting goods, camping gear, and outdoor equipment",
    "type": "Outflow",
    "second_category": "Outdoor Equipment",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 54,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_SUPERSTORES": {
    "name": "GENERAL_MERCHANDISE_SUPERSTORES",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_SUPERSTORES",
    "description": "Superstores such as Target and Walmart, selling both groceries and general merchandise",
    "type": "Outflow",
    "second_category": "Superstores",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 55,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE": {
    "name": "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE",
    "description": "Purchases for tobacco and vaping products",
    "type": "Outflow",
    "second_category": "Tobacco and Vape",
    "first_category": "Tobacco and Vape",
    "overall_category": "Tobacco and Vape",
    "overallCategoryId": "tobacco_and_vape",
    "firstCategoryId": "tobacco_and_vape",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 56,
    "isActive": true
  },
  "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE": {
    "name": "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
    "primary_plaid_category": "GENERAL_MERCHANDISE",
    "detailed_plaid_category": "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
    "description": "Other miscellaneous merchandise, including toys, hobbies, and arts and crafts",
    "type": "Outflow",
    "second_category": "Toys and Hobbies",
    "first_category": "Shopping",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "shopping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 57,
    "isActive": true
  },
  "HOME_IMPROVEMENT_FURNITURE": {
    "name": "HOME_IMPROVEMENT_FURNITURE",
    "primary_plaid_category": "HOME_IMPROVEMENT",
    "detailed_plaid_category": "HOME_IMPROVEMENT_FURNITURE",
    "description": "Furniture, bedding, and home accessories",
    "type": "Outflow",
    "second_category": "Furniture",
    "first_category": "Home Goods",
    "overall_category": "Shopping",
    "overallCategoryId": "shopping",
    "firstCategoryId": "home_goods",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 58,
    "isActive": true
  },
  "HOME_IMPROVEMENT_HARDWARE": {
    "name": "HOME_IMPROVEMENT_HARDWARE",
    "primary_plaid_category": "HOME_IMPROVEMENT",
    "detailed_plaid_category": "HOME_IMPROVEMENT_HARDWARE",
    "description": "Building materials, hardware stores, paint, and wallpaper",
    "type": "Outflow",
    "second_category": "Hardware and Materials",
    "first_category": "Home Improvement",
    "overall_category": "Home Improvement",
    "overallCategoryId": "home_improvement",
    "firstCategoryId": "home_improvement",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 59,
    "isActive": true
  },
  "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE": {
    "name": "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE",
    "primary_plaid_category": "HOME_IMPROVEMENT",
    "detailed_plaid_category": "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE",
    "description": "Plumbing, lighting, gardening, and roofing",
    "type": "Outflow",
    "second_category": "Home Repair",
    "first_category": "Home Improvement",
    "overall_category": "Home Improvement",
    "overallCategoryId": "home_improvement",
    "firstCategoryId": "home_improvement",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 60,
    "isActive": true
  },
  "HOME_IMPROVEMENT_SECURITY": {
    "name": "HOME_IMPROVEMENT_SECURITY",
    "primary_plaid_category": "HOME_IMPROVEMENT",
    "detailed_plaid_category": "HOME_IMPROVEMENT_SECURITY",
    "description": "Home security system purchases",
    "type": "Outflow",
    "second_category": "Home Security",
    "first_category": "Home Improvement",
    "overall_category": "Home Improvement",
    "overallCategoryId": "home_improvement",
    "firstCategoryId": "home_improvement",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 61,
    "isActive": true
  },
  "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT": {
    "name": "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT",
    "primary_plaid_category": "HOME_IMPROVEMENT",
    "detailed_plaid_category": "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT",
    "description": "Other miscellaneous home purchases, including pool installation and pest control",
    "type": "Outflow",
    "second_category": "Home Improvement",
    "first_category": "Home Improvement",
    "overall_category": "Home Improvement",
    "overallCategoryId": "home_improvement",
    "firstCategoryId": "home_improvement",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 62,
    "isActive": true
  },
  "MEDICAL_DENTAL_CARE": {
    "name": "MEDICAL_DENTAL_CARE",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_DENTAL_CARE",
    "description": "Dentists and general dental care",
    "type": "Outflow",
    "second_category": "Dental",
    "first_category": "Dental",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "dental",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 63,
    "isActive": true
  },
  "MEDICAL_EYE_CARE": {
    "name": "MEDICAL_EYE_CARE",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_EYE_CARE",
    "description": "Optometrists, contacts, and glasses stores",
    "type": "Outflow",
    "second_category": "Medical - Eye",
    "first_category": "Medical",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "medical",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 64,
    "isActive": true
  },
  "MEDICAL_NURSING_CARE": {
    "name": "MEDICAL_NURSING_CARE",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_NURSING_CARE",
    "description": "Nursing care and facilities",
    "type": "Outflow",
    "second_category": "Nursing Care",
    "first_category": "Medical",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "medical",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 65,
    "isActive": true
  },
  "MEDICAL_PHARMACIES_AND_SUPPLEMENTS": {
    "name": "MEDICAL_PHARMACIES_AND_SUPPLEMENTS",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_PHARMACIES_AND_SUPPLEMENTS",
    "description": "Pharmacies and nutrition shops",
    "type": "Outflow",
    "second_category": "Pharmacy",
    "first_category": "Medical",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "medical",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 66,
    "isActive": true
  },
  "MEDICAL_PRIMARY_CARE": {
    "name": "MEDICAL_PRIMARY_CARE",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_PRIMARY_CARE",
    "description": "Doctors and physicians",
    "type": "Outflow",
    "second_category": "Primary Care",
    "first_category": "Medical",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "medical",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 67,
    "isActive": true
  },
  "MEDICAL_VETERINARY_SERVICES": {
    "name": "MEDICAL_VETERINARY_SERVICES",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_VETERINARY_SERVICES",
    "description": "Prevention and care procedures for animals",
    "type": "Outflow",
    "second_category": "Veterinary",
    "first_category": "Medical",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "medical",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 68,
    "isActive": true
  },
  "MEDICAL_OTHER_MEDICAL": {
    "name": "MEDICAL_OTHER_MEDICAL",
    "primary_plaid_category": "MEDICAL",
    "detailed_plaid_category": "MEDICAL_OTHER_MEDICAL",
    "description": "Other miscellaneous medical, including blood work, hospitals, and ambulances",
    "type": "Outflow",
    "second_category": "Medical",
    "first_category": "Medical",
    "overall_category": "Medical",
    "overallCategoryId": "medical",
    "firstCategoryId": "medical",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 69,
    "isActive": true
  },
  "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS": {
    "name": "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
    "primary_plaid_category": "PERSONAL_CARE",
    "detailed_plaid_category": "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
    "description": "Gyms, fitness centers, and workout classes",
    "type": "Outflow",
    "second_category": "Fitness",
    "first_category": "Personal Care",
    "overall_category": "Personal Care",
    "overallCategoryId": "personal_care",
    "firstCategoryId": "personal_care",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 70,
    "isActive": true
  },
  "PERSONAL_CARE_HAIR_AND_BEAUTY": {
    "name": "PERSONAL_CARE_HAIR_AND_BEAUTY",
    "primary_plaid_category": "PERSONAL_CARE",
    "detailed_plaid_category": "PERSONAL_CARE_HAIR_AND_BEAUTY",
    "description": "Manicures, haircuts, waxing, spa/massages, and bath and beauty products ",
    "type": "Outflow",
    "second_category": "Hair and Beauty",
    "first_category": "Personal Care",
    "overall_category": "Personal Care",
    "overallCategoryId": "personal_care",
    "firstCategoryId": "personal_care",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 71,
    "isActive": true
  },
  "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING": {
    "name": "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING",
    "primary_plaid_category": "PERSONAL_CARE",
    "detailed_plaid_category": "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING",
    "description": "Wash and fold, and dry cleaning expenses",
    "type": "Outflow",
    "second_category": "Laundry and Dry Cleaning",
    "first_category": "Personal Care",
    "overall_category": "Personal Care",
    "overallCategoryId": "personal_care",
    "firstCategoryId": "personal_care",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 72,
    "isActive": true
  },
  "PERSONAL_CARE_OTHER_PERSONAL_CARE": {
    "name": "PERSONAL_CARE_OTHER_PERSONAL_CARE",
    "primary_plaid_category": "PERSONAL_CARE",
    "detailed_plaid_category": "PERSONAL_CARE_OTHER_PERSONAL_CARE",
    "description": "Other miscellaneous personal care, including mental health apps and services",
    "type": "Outflow",
    "second_category": "Personal Care",
    "first_category": "Personal Care",
    "overall_category": "Personal Care",
    "overallCategoryId": "personal_care",
    "firstCategoryId": "personal_care",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 73,
    "isActive": true
  },
  "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING": {
    "name": "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
    "description": "Financial planning, and tax and accounting services",
    "type": "Outflow",
    "second_category": "Financial Services",
    "first_category": "Financial Services",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "financial_services",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 74,
    "isActive": true
  },
  "GENERAL_SERVICES_AUTOMOTIVE": {
    "name": "GENERAL_SERVICES_AUTOMOTIVE",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_AUTOMOTIVE",
    "description": "Oil changes, car washes, repairs, and towing",
    "type": "Outflow",
    "second_category": "Automotive",
    "first_category": "Car Services",
    "overall_category": "Automotive",
    "overallCategoryId": "automotive",
    "firstCategoryId": "car_services",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 75,
    "isActive": true
  },
  "GENERAL_SERVICES_CHILDCARE": {
    "name": "GENERAL_SERVICES_CHILDCARE",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_CHILDCARE",
    "description": "Babysitters and daycare",
    "type": "Outflow",
    "second_category": "Childcare",
    "first_category": "Childcare",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "childcare",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 76,
    "isActive": true
  },
  "GENERAL_SERVICES_CONSULTING_AND_LEGAL": {
    "name": "GENERAL_SERVICES_CONSULTING_AND_LEGAL",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_CONSULTING_AND_LEGAL",
    "description": "Consulting and legal services",
    "type": "Outflow",
    "second_category": "Legal Services",
    "first_category": "Legal Services",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "legal_services",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 77,
    "isActive": true
  },
  "GENERAL_SERVICES_EDUCATION": {
    "name": "GENERAL_SERVICES_EDUCATION",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_EDUCATION",
    "description": "Elementary, high school, professional schools, and college tuition",
    "type": "Outflow",
    "second_category": "Tuition",
    "first_category": "Academic Services",
    "overall_category": "Academic Services",
    "overallCategoryId": "academic_services",
    "firstCategoryId": "academic_services",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 78,
    "isActive": true
  },
  "GENERAL_SERVICES_INSURANCE": {
    "name": "GENERAL_SERVICES_INSURANCE",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_INSURANCE",
    "description": "Insurance for auto, home, and healthcare",
    "type": "Outflow",
    "second_category": "Insurance",
    "first_category": "Insurance",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "insurance",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 79,
    "isActive": true
  },
  "GENERAL_SERVICES_POSTAGE_AND_SHIPPING": {
    "name": "GENERAL_SERVICES_POSTAGE_AND_SHIPPING",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_POSTAGE_AND_SHIPPING",
    "description": "Mail, packaging, and shipping services",
    "type": "Outflow",
    "second_category": "Postage and Shipping",
    "first_category": "Postage and Shipping",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "postage_and_shipping",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 80,
    "isActive": true
  },
  "GENERAL_SERVICES_STORAGE": {
    "name": "GENERAL_SERVICES_STORAGE",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_STORAGE",
    "description": "Storage services and facilities",
    "type": "Outflow",
    "second_category": "Storage Services",
    "first_category": "Storage Services",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "storage_services",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 81,
    "isActive": true
  },
  "GENERAL_SERVICES_OTHER_GENERAL_SERVICES": {
    "name": "GENERAL_SERVICES_OTHER_GENERAL_SERVICES",
    "primary_plaid_category": "GENERAL_SERVICES",
    "detailed_plaid_category": "GENERAL_SERVICES_OTHER_GENERAL_SERVICES",
    "description": "Other miscellaneous services, including advertising and cloud storage ",
    "type": "Outflow",
    "second_category": "Services",
    "first_category": "Other Services",
    "overall_category": "Services",
    "overallCategoryId": "services",
    "firstCategoryId": "other_services",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 82,
    "isActive": true
  },
  "GOVERNMENT_AND_NON_PROFIT_DONATIONS": {
    "name": "GOVERNMENT_AND_NON_PROFIT_DONATIONS",
    "primary_plaid_category": "GOVERNMENT_AND_NON_PROFIT",
    "detailed_plaid_category": "GOVERNMENT_AND_NON_PROFIT_DONATIONS",
    "description": "Charitable, political, and religious donations",
    "type": "Outflow",
    "second_category": "Charitable Donation",
    "first_category": "Non-Profit",
    "overall_category": "Charitable Giving",
    "overallCategoryId": "charitable_giving",
    "firstCategoryId": "non_profit",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 83,
    "isActive": true
  },
  "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES": {
    "name": "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES",
    "primary_plaid_category": "GOVERNMENT_AND_NON_PROFIT",
    "detailed_plaid_category": "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES",
    "description": "Government departments and agencies, such as driving licences, and passport renewal",
    "type": "Outflow",
    "second_category": "Government Identification",
    "first_category": "Government",
    "overall_category": "Government Payments",
    "overallCategoryId": "government_payments",
    "firstCategoryId": "government",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 84,
    "isActive": true
  },
  "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT": {
    "name": "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
    "primary_plaid_category": "GOVERNMENT_AND_NON_PROFIT",
    "detailed_plaid_category": "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
    "description": "Tax payments, including income and property taxes",
    "type": "Outflow",
    "second_category": "Taxes",
    "first_category": "Government",
    "overall_category": "Government Payments",
    "overallCategoryId": "government_payments",
    "firstCategoryId": "government",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 85,
    "isActive": true
  },
  "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT": {
    "name": "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT",
    "primary_plaid_category": "GOVERNMENT_AND_NON_PROFIT",
    "detailed_plaid_category": "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT",
    "description": "Other miscellaneous government and non-profit agencies",
    "type": "Outflow",
    "second_category": "Government",
    "first_category": "Government",
    "overall_category": "Government Payments",
    "overallCategoryId": "government_payments",
    "firstCategoryId": "government",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 86,
    "isActive": true
  },
  "TRANSPORTATION_BIKES_AND_SCOOTERS": {
    "name": "TRANSPORTATION_BIKES_AND_SCOOTERS",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_BIKES_AND_SCOOTERS",
    "description": "Bike and scooter rentals",
    "type": "Outflow",
    "second_category": "Bike and Scooter Rentals",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 87,
    "isActive": true
  },
  "TRANSPORTATION_GAS": {
    "name": "TRANSPORTATION_GAS",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_GAS",
    "description": "Purchases at a gas station",
    "type": "Outflow",
    "second_category": "Gas",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 88,
    "isActive": true
  },
  "TRANSPORTATION_PARKING": {
    "name": "TRANSPORTATION_PARKING",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_PARKING",
    "description": "Parking fees and expenses",
    "type": "Outflow",
    "second_category": "Parking Payment",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 89,
    "isActive": true
  },
  "TRANSPORTATION_PUBLIC_TRANSIT": {
    "name": "TRANSPORTATION_PUBLIC_TRANSIT",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_PUBLIC_TRANSIT",
    "description": "Public transportation, including rail and train, buses, and metro",
    "type": "Outflow",
    "second_category": "Public Transit",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 90,
    "isActive": true
  },
  "TRANSPORTATION_TAXIS_AND_RIDE_SHARES": {
    "name": "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
    "description": "Taxi and ride share services",
    "type": "Outflow",
    "second_category": "Taxis and Rideshares",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 91,
    "isActive": true
  },
  "TRANSPORTATION_TOLLS": {
    "name": "TRANSPORTATION_TOLLS",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_TOLLS",
    "description": "Toll expenses",
    "type": "Outflow",
    "second_category": "Road Tolls",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 92,
    "isActive": true
  },
  "TRANSPORTATION_OTHER_TRANSPORTATION": {
    "name": "TRANSPORTATION_OTHER_TRANSPORTATION",
    "primary_plaid_category": "TRANSPORTATION",
    "detailed_plaid_category": "TRANSPORTATION_OTHER_TRANSPORTATION",
    "description": "Other miscellaneous transportation expenses",
    "type": "Outflow",
    "second_category": "Other Transportation Costs",
    "first_category": "Transportation",
    "overall_category": "Transportation",
    "overallCategoryId": "transportation",
    "firstCategoryId": "transportation",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 93,
    "isActive": true
  },
  "TRAVEL_FLIGHTS": {
    "name": "TRAVEL_FLIGHTS",
    "primary_plaid_category": "TRAVEL",
    "detailed_plaid_category": "TRAVEL_FLIGHTS",
    "description": "Airline expenses",
    "type": "Outflow",
    "second_category": "Airlines",
    "first_category": "Travel",
    "overall_category": "Travel",
    "overallCategoryId": "travel",
    "firstCategoryId": "travel",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 94,
    "isActive": true
  },
  "TRAVEL_LODGING": {
    "name": "TRAVEL_LODGING",
    "primary_plaid_category": "TRAVEL",
    "detailed_plaid_category": "TRAVEL_LODGING",
    "description": "Hotels, motels, and hosted accommodation such as Airbnb",
    "type": "Outflow",
    "second_category": "Hotels",
    "first_category": "Travel",
    "overall_category": "Travel",
    "overallCategoryId": "travel",
    "firstCategoryId": "travel",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 95,
    "isActive": true
  },
  "TRAVEL_RENTAL_CARS": {
    "name": "TRAVEL_RENTAL_CARS",
    "primary_plaid_category": "TRAVEL",
    "detailed_plaid_category": "TRAVEL_RENTAL_CARS",
    "description": "Rental cars, charter buses, and trucks",
    "type": "Outflow",
    "second_category": "Rental Cars",
    "first_category": "Travel",
    "overall_category": "Travel",
    "overallCategoryId": "travel",
    "firstCategoryId": "travel",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 96,
    "isActive": true
  },
  "TRAVEL_OTHER_TRAVEL": {
    "name": "TRAVEL_OTHER_TRAVEL",
    "primary_plaid_category": "TRAVEL",
    "detailed_plaid_category": "TRAVEL_OTHER_TRAVEL",
    "description": "Other miscellaneous travel expenses",
    "type": "Outflow",
    "second_category": "Other Travel",
    "first_category": "Travel",
    "overall_category": "Travel",
    "overallCategoryId": "travel",
    "firstCategoryId": "travel",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 97,
    "isActive": true
  },
  "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY": {
    "name": "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
    "description": "Gas and electricity bills",
    "type": "Outflow",
    "second_category": "Gas and Electricity",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 98,
    "isActive": true
  },
  "RENT_AND_UTILITIES_INTERNET_AND_CABLE": {
    "name": "RENT_AND_UTILITIES_INTERNET_AND_CABLE",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_INTERNET_AND_CABLE",
    "description": "Internet and cable bills",
    "type": "Outflow",
    "second_category": "Internet and Cable",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 99,
    "isActive": true
  },
  "RENT_AND_UTILITIES_RENT": {
    "name": "RENT_AND_UTILITIES_RENT",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_RENT",
    "description": "Rent payment",
    "type": "Outflow",
    "second_category": "Rent",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 100,
    "isActive": true
  },
  "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT": {
    "name": "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT",
    "description": "Sewage and garbage disposal bills",
    "type": "Outflow",
    "second_category": "Sewage and Garbage",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 101,
    "isActive": true
  },
  "RENT_AND_UTILITIES_TELEPHONE": {
    "name": "RENT_AND_UTILITIES_TELEPHONE",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_TELEPHONE",
    "description": "Cell phone bills",
    "type": "Outflow",
    "second_category": "Cell Phone",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 102,
    "isActive": true
  },
  "RENT_AND_UTILITIES_WATER": {
    "name": "RENT_AND_UTILITIES_WATER",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_WATER",
    "description": "Water bills",
    "type": "Outflow",
    "second_category": "Water Bill",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 103,
    "isActive": true
  },
  "RENT_AND_UTILITIES_OTHER_UTILITIES": {
    "name": "RENT_AND_UTILITIES_OTHER_UTILITIES",
    "primary_plaid_category": "RENT_AND_UTILITIES",
    "detailed_plaid_category": "RENT_AND_UTILITIES_OTHER_UTILITIES",
    "description": "Other miscellaneous utility bills",
    "type": "Outflow",
    "second_category": "Other Bills",
    "first_category": "Utilities",
    "overall_category": "Rent and Utilities",
    "overallCategoryId": "rent_and_utilities",
    "firstCategoryId": "utilities",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 104,
    "isActive": true
  },
  "OTHER_OTHER": {
    "name": "OTHER_OTHER",
    "primary_plaid_category": "OTHER",
    "detailed_plaid_category": "OTHER_OTHER",
    "description": "Uncategorized / other transactions",
    "type": "Outflow",
    "second_category": "Uncategorized",
    "first_category": "Other",
    "overall_category": "Other",
    "overallCategoryId": "other",
    "firstCategoryId": "other",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 200,
    "isActive": true
  },
  "INCOME_SALARY": {
    "name": "INCOME_SALARY",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_SALARY",
    "description": "Salary income",
    "type": "Income",
    "second_category": "Salary",
    "first_category": "Wages",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "wages",
    "visible_by_default": true,
    "budget_selection": false,
    "income_selection": true,
    "index": 201,
    "isActive": true
  },
  "INCOME_OTHER": {
    "name": "INCOME_OTHER",
    "primary_plaid_category": "INCOME",
    "detailed_plaid_category": "INCOME_OTHER",
    "description": "Other income",
    "type": "Income",
    "second_category": "Other Income",
    "first_category": "Other Income",
    "overall_category": "Income",
    "overallCategoryId": "income",
    "firstCategoryId": "other_income",
    "visible_by_default": true,
    "budget_selection": false,
    "income_selection": true,
    "index": 202,
    "isActive": true
  },
  "TRANSFER_OUT_TRANSFER_OUT_FROM_APPS": {
    "name": "TRANSFER_OUT_TRANSFER_OUT_FROM_APPS",
    "primary_plaid_category": "TRANSFER_OUT",
    "detailed_plaid_category": "TRANSFER_OUT_TRANSFER_OUT_FROM_APPS",
    "description": "Outbound transfer via payment apps",
    "type": "Outflow",
    "second_category": "App Transfer",
    "first_category": "Outbound Transfer",
    "overall_category": "Outbound Account Transfer",
    "overallCategoryId": "outbound_account_transfer",
    "firstCategoryId": "outbound_transfer",
    "visible_by_default": true,
    "budget_selection": false,
    "income_selection": false,
    "index": 203,
    "isActive": true
  },
  "TRANSFER_IN_TRANSFER_IN_FROM_APPS": {
    "name": "TRANSFER_IN_TRANSFER_IN_FROM_APPS",
    "primary_plaid_category": "TRANSFER_IN",
    "detailed_plaid_category": "TRANSFER_IN_TRANSFER_IN_FROM_APPS",
    "description": "Inbound transfer via payment apps",
    "type": "Income",
    "second_category": "App Transfer",
    "first_category": "Inbound Transfer",
    "overall_category": "Inbound Account Transfer",
    "overallCategoryId": "inbound_account_transfer",
    "firstCategoryId": "inbound_transfer",
    "visible_by_default": true,
    "budget_selection": false,
    "income_selection": false,
    "index": 204,
    "isActive": true
  },
  "LOAN_PAYMENTS_BNPL": {
    "name": "LOAN_PAYMENTS_BNPL",
    "primary_plaid_category": "LOAN_PAYMENTS",
    "detailed_plaid_category": "LOAN_PAYMENTS_BNPL",
    "description": "Buy Now Pay Later installment payments",
    "type": "Outflow",
    "second_category": "Buy Now Pay Later",
    "first_category": "Loan Payment",
    "overall_category": "Loan Payment",
    "overallCategoryId": "loan_payment",
    "firstCategoryId": "loan_payment",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 205,
    "isActive": true
  },
  "OTHER_EXPENSE": {
    "name": "OTHER_EXPENSE",
    "primary_plaid_category": "OTHER",
    "detailed_plaid_category": "OTHER_EXPENSE",
    "description": "Default bucket for transactions with no/unknown category",
    "type": "Outflow",
    "second_category": "Uncategorized",
    "first_category": "Other",
    "overall_category": "Other",
    "overallCategoryId": "other",
    "firstCategoryId": "other",
    "visible_by_default": true,
    "budget_selection": true,
    "income_selection": false,
    "index": 206,
    "isActive": true
  }
};

// Categories upload function
export const uploadCategoriesData = onCall({ cors: true }, async (request) => {
  // 1. Authentication check
  if (!request.auth) {
    console.error('❌ [uploadCategoriesData] Unauthenticated request');
    throw new HttpsError('unauthenticated', 'User must be authenticated');
  }

  // 2. Admin role check — this overwrites the entire categories collection
  const isAdmin = request.auth.token?.role === 'admin';
  if (!isAdmin) {
    console.error(`❌ [uploadCategoriesData] Non-admin user attempted upload: ${request.auth.uid}`);
    throw new HttpsError('permission-denied', 'Only admins can upload categories');
  }

  try {
    console.log(`Starting categories upload... (admin: ${request.auth.uid})`);
    const db = getFirestore();

    const fullCategoriesData = CATEGORIES_DATA;
    const categories = Object.keys(fullCategoriesData) as (keyof typeof fullCategoriesData)[];
    const batchSize = 500;
    let uploadedCount = 0;

    for (let i = 0; i < categories.length; i += batchSize) {
      const batch = db.batch();
      const batchCategories = categories.slice(i, i + batchSize);

      batchCategories.forEach((categoryId) => {
        const categoryRef = db.collection('categories').doc(categoryId);
        // merge:true — never destroy out-of-band fields (e.g. the *CategoryId slugs).
        batch.set(categoryRef, {
          ...fullCategoriesData[categoryId],
          isActive: true,
        }, { merge: true });
      });

      await batch.commit();
      uploadedCount += batchCategories.length;
      console.log(`Uploaded batch: ${uploadedCount}/${categories.length} categories`);
    }

    console.log(`Successfully uploaded all ${uploadedCount} categories`);
    return { success: true, count: uploadedCount };
  } catch (error) {
    console.error('Error uploading categories:', error);
    throw new HttpsError('internal', 'Failed to upload categories: ' + (error as Error).message);
  }
});
